// Package materializer regenerates static instruction files for push-model
// agents (copilot, cursor, windsurf) from confirmed project memories.
//
// Phase 4.2 (Mpratyush54/nexus#16):
//   - Trigger: MEMORY_CONFIRMED / MEMORY_SUPERSEDED events via Store.Subscribe.
//   - Debounce: 5s quiet period after the last trigger before regenerating,
//     so batch confirmations produce one write, not N.
//   - Render: memories formatted to markdown/text within the agent's budget.
//   - Managed section: generated content lives between BEGIN/END delimiters;
//     user content outside is preserved byte-for-byte.
//   - Watcher hook: edits outside the managed section are reported as a
//     PROPOSED memory candidate (passive extraction input).
//
// Stdlib only. File I/O is injected (ReadFunc/WriteFunc) so the workspace
// daemon sandbox owns the real writes and unit tests use maps.
package materializer

import (
	"context"
	"errors"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"central-memory/internal/store"
)

// Managed-section delimiters. The em dash matches the plan §4.2 verbatim;
// ParseManaged also accepts the ASCII "--" variant for robustness.
const (
	BeginMarker    = "<!-- BEGIN CENTRAL MEMORY — DO NOT EDIT -->"
	EndMarker      = "<!-- END CENTRAL MEMORY -->"
	BeginMarkerAlt = "<!-- BEGIN CENTRAL MEMORY -- DO NOT EDIT -->"
	EndMarkerAlt   = "<!-- END CENTRAL MEMORY -->"
)

// Debounce is the quiet period after the last trigger event before the
// materializer regenerates files (issue #16: 5 seconds).
const Debounce = 5 * time.Second

// Trigger events that schedule a regeneration.
const (
	EventConfirmed  = "MEMORY_CONFIRMED"
	EventSuperseded = "MEMORY_SUPERSEDED"
)

// ShouldTrigger reports whether an event type schedules regeneration.
func ShouldTrigger(eventType string) bool {
	return eventType == EventConfirmed || eventType == EventSuperseded
}

// MemorySource abstracts confirmed-memory retrieval. *store.MemStore and
// *store.PostgresStore both satisfy it via SearchMemory; tests use a stub.
type MemorySource interface {
	SearchMemory(ctx context.Context, projectID string, query string, tags []string, limit int) ([]*store.MemoryItem, error)
}

// EventBus abstracts the real-time fan-out (store.Store already has it).
type EventBus interface {
	Subscribe(ctx context.Context, projectID string) (<-chan *store.Event, func(), error)
}

// RenderMarkdown formats confirmed memories as Markdown within budget
// chars. Items are ordered project → personal → session? No: caller order
// is preserved except CONFIRMED-first; over-budget trailing items are
// dropped so output never exceeds budget.
func RenderMarkdown(items []*store.MemoryItem, budget int) string {
	if budget <= 0 {
		return ""
	}
	confirmed := confirmedFirst(items)
	var b strings.Builder
	b.WriteString("# Project Memory (generated by Central Memory)\n\n")
	for _, m := range confirmed {
		line := "- **" + m.Key + "** (" + m.Scope + "): " + strings.TrimSpace(m.Content) + "\n"
		if b.Len()+len(line) > budget {
			break
		}
		b.WriteString(line)
	}
	out := b.String()
	if len(out) > budget {
		out = out[:budget]
	}
	return out
}

// RenderText formats confirmed memories as plain text (for .cursorrules /
// .windsurfrules) within budget chars.
func RenderText(items []*store.MemoryItem, budget int) string {
	if budget <= 0 {
		return ""
	}
	confirmed := confirmedFirst(items)
	var b strings.Builder
	for _, m := range confirmed {
		line := m.Key + ": " + strings.TrimSpace(m.Content) + "\n"
		if b.Len()+len(line) > budget {
			break
		}
		b.WriteString(line)
	}
	out := b.String()
	if len(out) > budget {
		out = out[:budget]
	}
	return out
}

func confirmedFirst(items []*store.MemoryItem) []*store.MemoryItem {
	out := make([]*store.MemoryItem, 0, len(items))
	for _, m := range items {
		if m != nil && m.Status == "CONFIRMED" {
			out = append(out, m)
		}
	}
	rest := make([]*store.MemoryItem, 0, len(items))
	for _, m := range items {
		if m != nil && m.Status != "CONFIRMED" {
			rest = append(rest, m)
		}
	}
	// Stable: keep caller order within each group.
	return append(out, rest...)
}

// ParseManaged splits file content into (pre, managed, post, found).
// found is false when no managed section exists.
func ParseManaged(content string) (pre, managed, post string, found bool) {
	begin, end := locateManaged(content)
	if begin < 0 {
		return content, "", "", false
	}
	pre = content[:begin]
	afterBegin := begin + len(matchedBegin(content[begin:]))
	closeIdx := strings.Index(content[afterBegin:], end)
	if closeIdx < 0 {
		return pre, content[afterBegin:], "", true
	}
	managed = content[afterBegin : afterBegin+closeIdx]
	post = content[afterBegin+closeIdx+len(end):]
	return pre, managed, post, true
}

func matchedBegin(s string) string {
	if strings.HasPrefix(s, BeginMarker) {
		return BeginMarker
	}
	return BeginMarkerAlt
}

func locateManaged(content string) (begin int, end string) {
	ib, ia := strings.Index(content, BeginMarker), strings.Index(content, BeginMarkerAlt)
	switch {
	case ib < 0 && ia < 0:
		return -1, EndMarker
	case ib >= 0 && (ia < 0 || ib < ia):
		return ib, EndMarker
	default:
		return ia, EndMarkerAlt
	}
}

// MergeManaged returns file content with generated placed inside the
// managed section. User content outside is preserved byte-for-byte. If no
// managed section exists, one is appended (separated by a blank line).
func MergeManaged(existing, generated string) string {
	pre, _, post, found := ParseManaged(existing)
	gen := strings.TrimRight(generated, "\n") + "\n"
	if !found {
		if strings.TrimSpace(existing) == "" {
			return BeginMarker + "\n" + gen + EndMarker + "\n"
		}
		trimmed := strings.TrimRight(existing, "\n")
		return trimmed + "\n\n" + BeginMarker + "\n" + gen + EndMarker + "\n"
	}
	// Normalize: exactly one trailing newline on pre when non-empty.
	if pre != "" && !strings.HasSuffix(pre, "\n") {
		pre += "\n"
	}
	out := pre + matchedBeginFor(existing) + "\n" + gen + matchedEndFor(existing)
	if post != "" && !strings.HasPrefix(post, "\n") {
		out += "\n"
	}
	return out + post
}

func matchedBeginFor(content string) string {
	ib, ia := strings.Index(content, BeginMarker), strings.Index(content, BeginMarkerAlt)
	if ib >= 0 && (ia < 0 || ib < ia) {
		return BeginMarker
	}
	if ia >= 0 {
		return BeginMarkerAlt
	}
	return BeginMarker
}

func matchedEndFor(content string) string {
	_, end := locateManaged(content)
	return end
}

// OutsideEditChanged reports whether content outside the managed section
// changed between two file states. The materializer ignores managed-section
// churn (its own writes); outside edits are user input.
func OutsideEditChanged(oldContent, newContent string) bool {
	oPre, _, oPost, _ := ParseManaged(oldContent)
	nPre, _, nPost, _ := ParseManaged(newContent)
	return oPre != nPre || oPost != nPost
}

// OutsideEditProposal extracts the user-written text outside the managed
// section of newContent when it differs from oldContent. Returns ("", false)
// when there is no outside change. The caller turns the text into a
// PROPOSED memory (watcher → INSTRUCTION_FILE_CHANGED → processor).
func OutsideEditProposal(oldContent, newContent string) (string, bool) {
	if !OutsideEditChanged(oldContent, newContent) {
		return "", false
	}
	nPre, _, nPost, _ := ParseManaged(newContent)
	oPre, _, oPost, _ := ParseManaged(oldContent)
	var parts []string
	if d := diffAddition(oPre, nPre); strings.TrimSpace(d) != "" {
		parts = append(parts, strings.TrimSpace(d))
	}
	if d := diffAddition(oPost, nPost); strings.TrimSpace(d) != "" {
		parts = append(parts, strings.TrimSpace(d))
	}
	proposal := strings.TrimSpace(strings.Join(parts, "\n"))
	if proposal == "" {
		// Content was deleted or only whitespace moved: still signal the
		// change with the full outside text so nothing is silently lost.
		proposal = strings.TrimSpace(nPre + "\n" + nPost)
	}
	if proposal == "" {
		return "", false
	}
	return proposal, true
}

// diffAddition returns lines present in next but not in prev (line-set
// diff; order of next preserved).
func diffAddition(prev, next string) string {
	have := make(map[string]bool)
	for _, l := range strings.Split(prev, "\n") {
		have[strings.TrimSpace(l)] = true
	}
	var added []string
	for _, l := range strings.Split(next, "\n") {
		if t := strings.TrimSpace(l); t != "" && !have[t] {
			added = append(added, l)
		}
	}
	return strings.Join(added, "\n")
}

// Target describes one push-model agent file to maintain.
type Target struct {
	AgentName string // copilot | cursor | windsurf
	FilePath  string // workspace-relative output file
	Format    string // markdown | text
	Budget    int    // chars
}

// DefaultTargets mirrors the push rows of 004_agents.up.sql.
func DefaultTargets() []Target {
	return []Target{
		{AgentName: "copilot", FilePath: ".github/copilot-instructions.md", Format: "markdown", Budget: 8000},
		{AgentName: "cursor", FilePath: ".cursorrules", Format: "text", Budget: 6000},
		{AgentName: "windsurf", FilePath: ".windsurfrules", Format: "text", Budget: 6000},
	}
}

// AddTarget validates and registers one push target (issue #41). Invalid
// targets fail before they can break Regenerate: blank agent names and
// paths, absolute paths (targets are workspace-relative), unknown formats,
// and non-positive budgets are rejected. Re-adding an existing FilePath
// replaces it so bootstrap code can override DefaultTargets per project.
func (m *Materializer) AddTarget(t Target) error {
	if strings.TrimSpace(t.AgentName) == "" {
		return errors.New("materializer: agent name is required")
	}
	if strings.TrimSpace(t.FilePath) == "" {
		return errors.New("materializer: file path is required")
	}
	// Targets are workspace-relative: reject absolute, rooted, and
	// volume-qualified paths on every OS (filepath.IsAbs alone misses
	// Unix-rooted "/x" on Windows, which still escapes the sandbox join).
	if filepath.IsAbs(t.FilePath) || filepath.VolumeName(t.FilePath) != "" ||
		strings.HasPrefix(t.FilePath, "/") || strings.HasPrefix(t.FilePath, `\`) {
		return errors.New("materializer: file path must be workspace-relative")
	}
	switch strings.ToLower(strings.TrimSpace(t.Format)) {
	case "markdown", "text":
	default:
		return errors.New("materializer: format must be markdown or text")
	}
	if t.Budget <= 0 {
		return errors.New("materializer: budget must be positive")
	}
	t.Format = strings.ToLower(strings.TrimSpace(t.Format))
	for i, cur := range m.Targets {
		if cur.FilePath == t.FilePath {
			m.Targets[i] = t
			return nil
		}
	}
	m.Targets = append(m.Targets, t)
	return nil
}

// Materializer subscribes to memory events and regenerates push files.
type Materializer struct {
	ProjectID string
	Targets   []Target
	Debounce  time.Duration

	// Injected collaborators (daemon sandbox owns real I/O).
	Source MemorySource
	Bus    EventBus
	Read   func(path string) (string, error)
	Write  func(path, content string) error
	// OnOutsideProposal, when set, receives (filePath, proposalText) for
	// outside-section edits detected by CheckFile.
	OnOutsideProposal func(filePath, proposal string)
}

// CheckFile reads one target file, detects outside-section user edits, and
// fires OnOutsideProposal. Used by the instruction-file watcher integration.
func (m *Materializer) CheckFile(ctx context.Context, t Target, oldContent string) error {
	if m.Read == nil {
		return nil
	}
	cur, err := m.Read(t.FilePath)
	if err != nil {
		return err
	}
	if proposal, ok := OutsideEditProposal(oldContent, cur); ok && m.OnOutsideProposal != nil {
		m.OnOutsideProposal(t.FilePath, proposal)
	}
	return nil
}

// Render selects the agent-specific formatter and caps to target budget.
func (m *Materializer) Render(t Target, items []*store.MemoryItem) string {
	// Highest-confidence first so truncation keeps the best signal.
	sorted := make([]*store.MemoryItem, 0, len(items))
	sorted = append(sorted, items...)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i] == nil || sorted[j] == nil {
			return sorted[j] == nil
		}
		return sorted[i].Confidence > sorted[j].Confidence
	})
	if strings.ToLower(t.Format) == "text" {
		return RenderText(sorted, t.Budget)
	}
	return RenderMarkdown(sorted, t.Budget)
}

// Regenerate fetches confirmed memories once and rewrites every target.
func (m *Materializer) Regenerate(ctx context.Context) error {
	if m.Source == nil {
		return nil
	}
	items, err := m.Source.SearchMemory(ctx, m.ProjectID, "", nil, 200)
	if err != nil {
		return err
	}
	for _, t := range m.Targets {
		generated := m.Render(t, items)
		var existing string
		if m.Read != nil {
			existing, _ = m.Read(t.FilePath) // missing file -> create fresh
		}
		merged := MergeManaged(existing, generated)
		if m.Write != nil {
			if err := m.Write(t.FilePath, merged); err != nil {
				return err
			}
		}
	}
	return nil
}

// Run subscribes to MEMORY_CONFIRMED/MEMORY_SUPERSEDED and regenerates
// after a Debounce quiet period. It returns when ctx is done. A closed bus
// channel resubscribes with backoff (issue #145) instead of exiting:
// silently stopping would freeze push files with no error.
func (m *Materializer) Run(ctx context.Context) error {
	if m.Bus == nil {
		<-ctx.Done()
		return ctx.Err()
	}
	wait := m.Debounce
	if wait <= 0 {
		wait = Debounce
	}
	backoff := wait
	const maxBackoff = 5 * time.Minute
	for ctx.Err() == nil {
		if err := m.runOnce(ctx, wait); err != nil {
			return err
		}
		// Bus closed beneath us: back off and resubscribe.
		backoff *= 2
		if backoff > maxBackoff {
			backoff = maxBackoff
		}
		t := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			t.Stop()
			return ctx.Err()
		case <-t.C:
		}
	}
	return ctx.Err()
}

// runOnce drains one subscription until ctx ends (nil) or the bus channel
// closes (non-nil return → caller resubscribes).
func (m *Materializer) runOnce(ctx context.Context, wait time.Duration) error {
	ch, cancel, err := m.Bus.Subscribe(ctx, m.ProjectID)
	if err != nil {
		return err
	}
	defer cancel()
	var timer *time.Timer
	var timerCh <-chan time.Time
	disarm := func() {
		if timer != nil {
			if !timer.Stop() {
				select {
				case <-timer.C:
				default:
				}
			}
			timer = nil
			timerCh = nil
		}
	}
	defer disarm()
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case ev, ok := <-ch:
			if !ok {
				return errBusClosed
			}
			if ev == nil || !ShouldTrigger(ev.EventType) {
				continue
			}
			disarm()
			timer = time.NewTimer(wait)
			timerCh = timer.C
		case <-timerCh:
			timerCh = nil
			timer = nil
			_ = m.Regenerate(ctx) // best-effort: next trigger retries
		}
	}
}

// errBusClosed signals runOnce to resubscribe (never surfaces to callers:
// Run loops until ctx ends).
var errBusClosed = errors.New("materializer: event bus closed beneath Run")
