// Generated from internal/core.Methods. Do not edit by hand.
public enum NxMethods {
    public static let timelineList = "timeline.list"
    public static let eventsSubscribe = "events.subscribe"
    public static let sessionsGet = "sessions.get"
    public static let sessionsTurns = "sessions.turns"
    public static let sessionsSummary = "sessions.summary"
    public static let filesRead = "files.read"
    public static let filesDiff = "files.diff"
    public static let continueStart = "continue.start"
    public static let memorySearch = "memory.search"
    public static let memoryForget = "memory.forget"
    public static let memoryPin = "memory.pin"
    public static let memoryScope = "memory.scope"
    public static let sessionsShare = "sessions.share"
    public static let uploadsStatus = "uploads.status"
    public static let uploadsRetry = "uploads.retry"
    public static let cacheClear = "cache.clear"
    public static let netStatus = "net.status"
    public static let teleportRedactionPreview = "teleport.redaction_preview"
    public static let teleportSend = "teleport.send"
    public static let teleportPrepare = "teleport.prepare"
    public static let statusGet = "status.get"
    public static let diagnosticsGet = "diagnostics.get"
    public static let authCallback = "auth.callback"
}
