# secrets.tf — DB strings + JWT keys via Secrets Manager (issue #20).
#
# Checklist item "Secrets Manager refs not hardcoded": NOTHING secret appears
# as a literal anywhere in this stack. Passwords/keys are generated by
# random_password into aws_secretsmanager_secret_version, and the ECS task
# (ecs.tf) consumes them via the `secrets` block (valueFrom = ARN), which
# lands in the container as environment variables at launch.

resource "random_password" "db_app" {
  length           = 32
  special          = true
  override_special = "-_"
}

resource "random_password" "jwt" {
  # HS256 key for server.Options.JWTSecret (>= 32 chars enforced by bootstrap).
  length           = 64
  special          = true
  override_special = "-_"
}

resource "aws_secretsmanager_secret" "db_app" {
  name                    = "${var.project}/db-app"
  description             = "App DB credentials for the central-memory server (issue #20)."
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "db_app" {
  secret_id = aws_secretsmanager_secret.db_app.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_app.result
    host     = aws_rds_cluster.main.endpoint
    port     = 5432
    dbname   = var.db_name
  })
}

resource "aws_secretsmanager_secret" "jwt" {
  name                    = "${var.project}/jwt"
  description             = "JWT signing key for the central-memory server (issue #20)."
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "jwt" {
  secret_id     = aws_secretsmanager_secret.jwt.id
  secret_string = jsonencode({ signing_key = random_password.jwt.result })
}
