// Agent registry (issue #15, plan §4.1).
//
// Agents are the pull/push consumers of memory: pull agents (Claude,
// OpenCode, Codex, Antigravity) read live context through the MCP server,
// while push agents (Copilot, Cursor, Windsurf) are served via materialized
// instruction files regenerated by the Phase-4 materializer. This file owns
// the read seam over migrations/004_agents: lookup by name, the per-project
// enabled set, budget resolution with default fallback, and the push-target
// (agent → output file) mapping.
//
// Context Builder integration: BudgetFor resolves the char budget the
// builder should assemble under for a named agent, falling back to
// context.DefaultBudgetChars for unknown agents — so the MCP/server layers
// can call store.BudgetFor without touching builder.go (which stays
// dependency-free per ADR-006; the import direction here is store →
// context, no cycle).
//
// Testability: AgentStore depends on the DBTX interface (db.go), so unit
// tests run without a live Postgres via a scripted fake. The seed table,
// budget fallback, push mapping, and project config overrides are pure and
// covered DB-free.
package store

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	ctxbuilder "central-memory/internal/context"

	"github.com/jackc/pgx/v5"
)

// Adapter types (CHECK constraint in migrations/004, plan §4.1).
const (
	// AdapterPull reads live context (MCP): claude, opencode, codex,
	// antigravity.
	AdapterPull = "pull"
	// AdapterPush is served materialized files: copilot, cursor, windsurf.
	AdapterPush = "push"
)

// IsValidAdapterType reports whether t is a known adapter type. Empty is
// invalid — agent rows always carry pull or push (NOT NULL + CHECK in 004).
func IsValidAdapterType(t string) bool {
	switch strings.ToLower(strings.TrimSpace(t)) {
	case AdapterPull, AdapterPush:
		return true
	default:
		return false
	}
}

// NormalizeAgentName lower-cases and trims an agent name. Seed names are
// lowercase; lookups normalize so "Claude" and " claude " still resolve.
func NormalizeAgentName(name string) string {
	return strings.ToLower(strings.TrimSpace(name))
}

// Agent mirrors an agents row (plan §4.1). Empty Capabilities/OutputFile/
// OutputFormat mean SQL NULL (pull agents carry no output file or format).
type Agent struct {
	ID            string
	Name          string
	AdapterType   string // pull | push
	Capabilities  string // raw JSON; "" = NULL
	ContextBudget int
	OutputFile    string // "" = NULL (pull agents)
	OutputFormat  string // "" = NULL (pull agents)
	CreatedAt     time.Time
}

// IsPull reports whether the agent reads live context through MCP.
func (a Agent) IsPull() bool { return a.AdapterType == AdapterPull }

// IsPush reports whether the agent is served materialized instruction files.
func (a Agent) IsPush() bool { return a.AdapterType == AdapterPush }

// SeedAgents is the Go mirror of the migrations/004 seed INSERT: four 10k
// pull agents, Copilot at 8k push, Cursor/Windsurf at 6k push with their
// plan §4.1 output files and formats. BudgetFor and PushTargets read this
// table so unit tests pin the seed contract DB-free.
var SeedAgents = []Agent{
	{Name: "claude", AdapterType: AdapterPull, ContextBudget: 10000},
	{Name: "opencode", AdapterType: AdapterPull, ContextBudget: 10000},
	{Name: "codex", AdapterType: AdapterPull, ContextBudget: 10000},
	{Name: "antigravity", AdapterType: AdapterPull, ContextBudget: 10000},
	{Name: "copilot", AdapterType: AdapterPush, ContextBudget: 8000, OutputFile: ".github/copilot-instructions.md", OutputFormat: "markdown"},
	{Name: "cursor", AdapterType: AdapterPush, ContextBudget: 6000, OutputFile: ".cursorrules", OutputFormat: "text"},
	{Name: "windsurf", AdapterType: AdapterPush, ContextBudget: 6000, OutputFile: ".windsurfrules", OutputFormat: "text"},
}

// seedBudgetByName indexes SeedAgents by normalized name for BudgetFor.
func seedBudgetByName() map[string]int {
	m := make(map[string]int, len(SeedAgents))
	for _, a := range SeedAgents {
		m[NormalizeAgentName(a.Name)] = a.ContextBudget
	}
	return m
}

// BudgetFor resolves the Context Builder char budget for a named agent:
// the seed budget when the agent is known, context.DefaultBudgetChars
// otherwise (unknown agents, empty names). Pure — the MCP/server layers
// call this without a database and without editing builder.go.
func BudgetFor(agentName string) int {
	if b, ok := seedBudgetByName()[NormalizeAgentName(agentName)]; ok && b > 0 {
		return b
	}
	return ctxbuilder.DefaultBudgetChars
}

// ParseBudgetOverride extracts a per-project budget override from a
// project_agents.config JSON document: {"context_budget": N}. It returns
// (N, true) only when the document parses and N is positive; anything else
// (empty, NULL-equivalent "", malformed JSON, missing or non-positive N)
// returns (0, false) so the caller falls through to the agent default.
// The parse is deliberately minimal (no encoding/json struct) to keep this
// file stdlib-only and obvious.
func ParseBudgetOverride(config string) (int, bool) {
	s := strings.TrimSpace(config)
	if s == "" || s == "{}" || strings.EqualFold(s, "null") {
		return 0, false
	}
	// Find "context_budget" key and read the integer that follows its colon.
	idx := strings.Index(s, `"context_budget"`)
	if idx < 0 {
		return 0, false
	}
	rest := s[idx+len(`"context_budget"`):]
	colon := strings.Index(rest, ":")
	if colon < 0 {
		return 0, false
	}
	num := strings.TrimSpace(rest[colon+1:])
	// Trim trailing JSON delimiters: the value runs to the next ',', '}',
	// whitespace, or quote boundary.
	end := strings.IndexAny(num, ",} \t\r\n\"")
	if end >= 0 {
		num = num[:end]
	}
	n := 0
	for _, c := range num {
		if c < '0' || c > '9' {
			return 0, false
		}
		n = n*10 + int(c-'0')
	}
	if num == "" || n <= 0 {
		return 0, false
	}
	return n, true
}

// EffectiveBudget resolves base against an optional project config
// override: a valid positive {"context_budget": N} wins, else base when
// positive, else context.DefaultBudgetChars. This is the single funnel for
// every budget decision — BudgetForProject and ProjectAgent.Budget both
// end here.
func EffectiveBudget(base int, config string) int {
	if n, ok := ParseBudgetOverride(config); ok {
		return n
	}
	if base > 0 {
		return base
	}
	return ctxbuilder.DefaultBudgetChars
}

// PushTargets maps push agents to their materializer output files
// (name → output_file). Pull agents and push agents without an output file
// are excluded — the materializer only regenerates files for entries in
// this map. Deterministic over the input order; a nil/empty input yields
// an empty (non-nil) map.
func PushTargets(agents []Agent) map[string]string {
	out := make(map[string]string)
	for _, a := range agents {
		if a.IsPush() && strings.TrimSpace(a.OutputFile) != "" {
			out[a.Name] = a.OutputFile
		}
	}
	return out
}

// ProjectAgent is one project_agents row joined with its agent: everything
// the materializer (output file + format) and budget resolution (budget +
// config override) need for one enabled agent in one project. Empty Config
// means SQL NULL — no per-project override.
type ProjectAgent struct {
	ProjectID     string
	AgentID       string
	AgentName     string
	AdapterType   string
	ContextBudget int
	OutputFile    string
	OutputFormat  string
	Enabled       bool
	Config        string // raw JSON override; "" = NULL
}

// Budget resolves this row's effective Context Builder budget: the config
// override wins, else the agent default, else context.DefaultBudgetChars.
func (p ProjectAgent) Budget() int {
	return EffectiveBudget(p.ContextBudget, p.Config)
}

// IsPush reports whether this project agent is served a materialized file.
func (p ProjectAgent) IsPush() bool { return p.AdapterType == AdapterPush }

// agentColumns selects agents with NULLs coalesced (except created_at,
// which is always set by DEFAULT now()).
const agentColumns = `id::TEXT AS id, ` +
	`name, ` +
	`adapter_type, ` +
	`COALESCE(capabilities::TEXT, '') AS capabilities, ` +
	`context_budget, ` +
	`COALESCE(output_file, '') AS output_file, ` +
	`COALESCE(output_format, '') AS output_format, ` +
	`created_at`

// projectAgentColumns selects the project_agents ⨝ agents join behind
// EnabledForProject/SetProjectAgent with NULLs coalesced.
const projectAgentColumns = `pa.project_id::TEXT AS project_id, ` +
	`pa.agent_id::TEXT AS agent_id, ` +
	`a.name AS agent_name, ` +
	`a.adapter_type, ` +
	`a.context_budget, ` +
	`COALESCE(a.output_file, '') AS output_file, ` +
	`COALESCE(a.output_format, '') AS output_format, ` +
	`COALESCE(pa.enabled, true) AS enabled, ` +
	`COALESCE(pa.config::TEXT, '') AS config`

// scanAgent scans a full agentColumns row.
func scanAgent(row pgx.Row) (*Agent, error) {
	var a Agent
	if err := row.Scan(
		&a.ID, &a.Name, &a.AdapterType, &a.Capabilities,
		&a.ContextBudget, &a.OutputFile, &a.OutputFormat,
		&a.CreatedAt,
	); err != nil {
		return nil, err
	}
	return &a, nil
}

// scanProjectAgent scans a full projectAgentColumns row.
func scanProjectAgent(row pgx.Row) (*ProjectAgent, error) {
	var p ProjectAgent
	if err := row.Scan(
		&p.ProjectID, &p.AgentID, &p.AgentName, &p.AdapterType,
		&p.ContextBudget, &p.OutputFile, &p.OutputFormat,
		&p.Enabled, &p.Config,
	); err != nil {
		return nil, err
	}
	return &p, nil
}

// AgentStore is the agent registry read seam plus per-project enablement.
type AgentStore struct {
	db DBTX
}

// NewAgentStore wires an AgentStore to any DBTX (pool, transaction, fake).
func NewAgentStore(db DBTX) *AgentStore {
	return &AgentStore{db: db}
}

// GetByName fetches one agent by name (case-insensitive: "Claude" finds
// "claude") or a wrapped ErrNotFound.
func (s *AgentStore) GetByName(ctx context.Context, name string) (*Agent, error) {
	normalized := NormalizeAgentName(name)
	if normalized == "" {
		return nil, errors.New("store: agent name is required")
	}
	a, err := scanAgent(s.db.QueryRow(ctx,
		`SELECT `+agentColumns+` FROM agents WHERE name = $1`, normalized))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("store: agent %q: %w", normalized, ErrNotFound)
		}
		return nil, fmt.Errorf("store: get agent: %w", err)
	}
	return a, nil
}

// List returns every registered agent ordered by name (stable order for
// the materializer fan-out and admin views).
func (s *AgentStore) List(ctx context.Context) ([]Agent, error) {
	rows, err := s.db.Query(ctx,
		`SELECT `+agentColumns+` FROM agents ORDER BY name ASC`)
	if err != nil {
		return nil, fmt.Errorf("store: list agents: %w", err)
	}
	defer rows.Close()
	var out []Agent
	for rows.Next() {
		var a Agent
		if err := rows.Scan(
			&a.ID, &a.Name, &a.AdapterType, &a.Capabilities,
			&a.ContextBudget, &a.OutputFile, &a.OutputFormat,
			&a.CreatedAt,
		); err != nil {
			return nil, fmt.Errorf("store: list agents scan: %w", err)
		}
		out = append(out, a)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: list agents rows: %w", err)
	}
	return out, nil
}

// EnabledForProject returns the explicitly enabled agents of a project,
// oldest-enablement order undefined — ordered by agent name for a stable
// materializer fan-out. A project with no project_agents rows yields an
// empty slice: absence means "no explicit per-project setting" (global
// seed defaults apply), not "everything enabled".
func (s *AgentStore) EnabledForProject(ctx context.Context, projectID string) ([]ProjectAgent, error) {
	if strings.TrimSpace(projectID) == "" {
		return nil, errors.New("store: project id is required")
	}
	rows, err := s.db.Query(ctx,
		`SELECT `+projectAgentColumns+`
		 FROM project_agents pa JOIN agents a ON a.id = pa.agent_id
		 WHERE pa.project_id = $1 AND pa.enabled
		 ORDER BY a.name ASC`,
		projectID)
	if err != nil {
		return nil, fmt.Errorf("store: enabled project agents: %w", err)
	}
	defer rows.Close()
	var out []ProjectAgent
	for rows.Next() {
		var p ProjectAgent
		if err := rows.Scan(
			&p.ProjectID, &p.AgentID, &p.AgentName, &p.AdapterType,
			&p.ContextBudget, &p.OutputFile, &p.OutputFormat,
			&p.Enabled, &p.Config,
		); err != nil {
			return nil, fmt.Errorf("store: enabled project agents scan: %w", err)
		}
		out = append(out, p)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: enabled project agents rows: %w", err)
	}
	return out, nil
}

// SetProjectAgent upserts one project's enablement + config for an agent
// (enabled defaults true in SQL; config "" stores NULL = no override) and
// returns the joined row. Disabling is an upsert with enabled = false, so
// opt-outs stay visible as rows rather than silent absences.
func (s *AgentStore) SetProjectAgent(ctx context.Context, projectID, agentID string, enabled bool, config string) (*ProjectAgent, error) {
	if strings.TrimSpace(projectID) == "" {
		return nil, errors.New("store: project id is required")
	}
	if strings.TrimSpace(agentID) == "" {
		return nil, errors.New("store: agent id is required")
	}
	var id string
	if err := s.db.QueryRow(ctx,
		`INSERT INTO project_agents (project_id, agent_id, enabled, config)
		 VALUES ($1, $2, $3, $4)
		 ON CONFLICT (project_id, agent_id)
		 DO UPDATE SET enabled = EXCLUDED.enabled, config = EXCLUDED.config
		 RETURNING agent_id::TEXT`,
		projectID, agentID, enabled, nullText(strings.TrimSpace(config))).Scan(&id); err != nil {
		return nil, fmt.Errorf("store: set project agent: %w", err)
	}
	p, err := scanProjectAgent(s.db.QueryRow(ctx,
		`SELECT `+projectAgentColumns+`
		 FROM project_agents pa JOIN agents a ON a.id = pa.agent_id
		 WHERE pa.project_id = $1 AND pa.agent_id = $2`,
		projectID, agentID))
	if err != nil {
		return nil, fmt.Errorf("store: read back project agent: %w", err)
	}
	return p, nil
}

// BudgetForProject resolves the Context Builder budget for an agent inside
// a project: the project's config override wins, else the agent's
// context_budget, else context.DefaultBudgetChars. Unknown agents fall back
// to the default without an error (same contract as BudgetFor) — only real
// database failures are returned as errors.
func (s *AgentStore) BudgetForProject(ctx context.Context, projectID, agentName string) (int, error) {
	normalized := NormalizeAgentName(agentName)
	if strings.TrimSpace(projectID) == "" {
		return 0, errors.New("store: project id is required")
	}
	if normalized == "" {
		return 0, errors.New("store: agent name is required")
	}
	var budget int
	var config string
	if err := s.db.QueryRow(ctx,
		`SELECT a.context_budget, COALESCE(pa.config::TEXT, '')
		 FROM agents a
		 LEFT JOIN project_agents pa
		   ON pa.agent_id = a.id AND pa.project_id = $1
		 WHERE a.name = $2`,
		projectID, normalized).Scan(&budget, &config); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return BudgetFor(normalized), nil
		}
		return 0, fmt.Errorf("store: budget for project agent: %w", err)
	}
	return EffectiveBudget(budget, config), nil
}

// PushTargetsForProject returns the materializer fan-out for a project:
// output file per enabled push agent (name → output_file). Pull agents
// never appear here — they read live context through MCP.
func (s *AgentStore) PushTargetsForProject(ctx context.Context, projectID string) (map[string]string, error) {
	enabled, err := s.EnabledForProject(ctx, projectID)
	if err != nil {
		return nil, err
	}
	out := make(map[string]string)
	for _, p := range enabled {
		if p.IsPush() && strings.TrimSpace(p.OutputFile) != "" {
			out[p.AgentName] = p.OutputFile
		}
	}
	return out, nil
}
